### ISSUE TITLE
容器启动失败

### ISSUE THREAD

**Issue by yunkuangao** [koishijs/boilerplate#29]
启动命令
`docker run --rm koishijs/koishi`

完整日志https://paste.yka.moe/?2404793a6e61cc9b#FFL7DP7wAf9SqZfhdiZMUae5u2QM5quKnd2XiMKnywVs
日志
```
Archive:  /boilerplate.zip
  inflating: .env
   creating: .yarn/
   creating: .yarn/cache/
  inflating: .yarn/cache/.gitignore
  inflating: .yarnrc.yml
  inflating: README.md
  inflating: koishi.yml
   creating: node_modules/
   creating: node_modules/picomatch/
  inflating: node_modules/picomatch/LICENSE
  inflating: node_modules/picomatch/index.js
  inflating: node_modules/picomatch/README.md
  inflating: node_modules/picomatch/CHANGELOG.md
   
  ... 类型的行为,因为comment长度限制,故截断中间部分,完整内容可查看上方的链接

  inflating: node_modules/form-data/package.json
   creating: node_modules/form-data/lib/
  inflating: node_modules/form-data/lib/form_data.js
  inflating: node_modules/form-data/lib/browser.js
  inflating: node_modules/form-data/lib/populate.js
  inflating: package.json
  inflating: yarn.lock
Internal Error: @koishijs/boilerplate@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at $x.resolve (/.yarn/releases/yarn-4.0.1.cjs:205:8435)
    at Bd.resolve (/.yarn/releases/yarn-4.0.1.cjs:141:1488)
    at /.yarn/releases/yarn-4.0.1.cjs:210:7182
    at Yy (/.yarn/releases/yarn-4.0.1.cjs:140:53922)
    at ne (/.yarn/releases/yarn-4.0.1.cjs:210:7162)
    at /.yarn/releases/yarn-4.0.1.cjs:210:7788
```

**Comment by yunkuangao** [comment]
版本为: [v1.11.2](https://hub.docker.com/layers/koishijs/koishi/v1.11.2/images/sha256-2a4c1b6447a8208cea4edb4481db4273a4f0546c2cc1c07949e5fa8a5f892acf?context=explore)

**Comment by shigma** [comment]
请尝试 1.11.3 版本。

**Comment by yunkuangao** [comment]
在 1.11.3版本下尝试
`docker run --rm koishijs/koishi:v1.11.3`

输出,完整日志 https://paste.yka.moe/?78db1aa6974b63ec#PsApPv1qEksoRKpW6dhPp7ACRnepP1g9qMS5pDEzw2U
```
Archive:  /boilerplate.zip
  inflating: .env
  inflating: .yarnrc.yml
  inflating: README.md
  inflating: koishi.yml
 
  ... 截断

  inflating: node_modules/form-data/lib/populate.js
  inflating: package.json
  inflating: yarn.lock
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/koishi/.yarn/releases/yarn-4.0.1.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.9.0
```

**Comment by shigma** [comment]
请尝试 1.11.4 版本。

**Comment by yunkuangao** [comment]
在 1.11.4 修复
